version: '3.3'
services:
  mongo:
    ports:
      - '27017:27017'
    container_name: test-mongo
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    image: mongo